# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "842285b54c003859a0ca5d6b5e1b74ad"
name = "Arktic - A/B Split test"
application_url = "https://app.arkticstudio.com"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_command = "npx react-router dev"
build_command = "npx react-router build"

[access_scopes]
scopes = "read_products,read_themes,write_themes,read_orders"

[auth]
redirect_urls = [
  "https://app.arkticstudio.com/auth/callback",
  "https://app.arkticstudio.com/auth/shopify/callback",
  "https://app.arkticstudio.com/api/auth/callback",
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["shop/update"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["orders/create", "orders/paid"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["orders/cancelled", "orders/updated"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["themes/create", "themes/update", "themes/delete"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["app_subscriptions/update"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks"



[pos]
embedded = false
