# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "842285b54c003859a0ca5d6b5e1b74ad"
name = "Split tester"
application_url = "https://amused-bravery-production-e9f7.up.railway.app"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_command = "npx react-router dev"
build_command = "npx react-router build"

[access_scopes]
scopes = "read_products,write_products,read_themes,write_themes,read_orders,write_orders,read_customers,read_content,write_content,read_price_rules,write_price_rules,read_script_tags,write_script_tags"

[auth]
redirect_urls = [
  "https://amused-bravery-production-e9f7.up.railway.app/auth/callback",
  "https://amused-bravery-production-e9f7.up.railway.app/auth/shopify/callback",
  "https://amused-bravery-production-e9f7.up.railway.app/api/auth/callback",
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["shop/update"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["orders/create", "orders/paid"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["orders/cancelled", "orders/updated"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["themes/create", "themes/update", "themes/delete"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/webhooks"



[pos]
embedded = false
