// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/config/:shopDomain": {
    params: {
      "shopDomain": string;
    };
  };
  "/storefront/embed.js": {
    params: {};
  };
  "/api/assign": {
    params: {};
  };
  "/api/events": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/experiments": {
    params: {};
  };
  "/dashboard/experiments/:id": {
    params: {
      "id": string;
    };
  };
  "/dashboard/experiments/:id/variants/:variantId": {
    params: {
      "id": string;
      "variantId": string;
    };
  };
  "/dashboard/experiments/new": {
    params: {};
  };
  "/dashboard/lift-assist": {
    params: {};
  };
  "/dashboard/segments": {
    params: {};
  };
  "/dashboard/segments/new": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
  "/dashboard/billing": {
    params: {};
  };
  "/dashboard/results": {
    params: {};
  };
  "/webhooks": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/experiments": {
    params: {};
  };
  "/app/experiments/:id": {
    params: {
      "id": string;
    };
  };
  "/app/experiments/:id/variants/:variantId": {
    params: {
      "id": string;
      "variantId": string;
    };
  };
  "/app/experiments/new": {
    params: {};
  };
  "/app/lift-assist": {
    params: {};
  };
  "/app/segments": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/billing": {
    params: {};
  };
  "/app/results": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/config/:shopDomain" | "/storefront/embed.js" | "/api/assign" | "/api/events" | "/dashboard" | "/dashboard/experiments" | "/dashboard/experiments/:id" | "/dashboard/experiments/:id/variants/:variantId" | "/dashboard/experiments/new" | "/dashboard/lift-assist" | "/dashboard/segments" | "/dashboard/segments/new" | "/dashboard/settings" | "/dashboard/billing" | "/dashboard/results" | "/webhooks" | "/auth/*" | "/app" | "/app/experiments" | "/app/experiments/:id" | "/app/experiments/:id/variants/:variantId" | "/app/experiments/new" | "/app/lift-assist" | "/app/segments" | "/app/settings" | "/app/billing" | "/app/results";
  };
  "routes/api.config.$shopDomain.ts": {
    id: "routes/api.config.$shopDomain";
    page: "/api/config/:shopDomain";
  };
  "routes/storefront.embed[.js].tsx": {
    id: "routes/storefront.embed[.js]";
    page: "/storefront/embed.js";
  };
  "routes/api.assign.tsx": {
    id: "routes/api.assign";
    page: "/api/assign";
  };
  "routes/api.events.tsx": {
    id: "routes/api.events";
    page: "/api/events";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/experiments" | "/dashboard/experiments/:id" | "/dashboard/experiments/:id/variants/:variantId" | "/dashboard/experiments/new" | "/dashboard/lift-assist" | "/dashboard/segments" | "/dashboard/segments/new" | "/dashboard/settings" | "/dashboard/billing" | "/dashboard/results";
  };
  "routes/dashboard.experiments.tsx": {
    id: "routes/dashboard.experiments";
    page: "/dashboard/experiments" | "/dashboard/experiments/:id" | "/dashboard/experiments/:id/variants/:variantId" | "/dashboard/experiments/new";
  };
  "routes/dashboard.experiments._index.tsx": {
    id: "routes/dashboard.experiments._index";
    page: "/dashboard/experiments";
  };
  "routes/dashboard.experiments.$id.tsx": {
    id: "routes/dashboard.experiments.$id";
    page: "/dashboard/experiments/:id" | "/dashboard/experiments/:id/variants/:variantId";
  };
  "routes/dashboard.experiments.$id.variants.$variantId.tsx": {
    id: "routes/dashboard.experiments.$id.variants.$variantId";
    page: "/dashboard/experiments/:id/variants/:variantId";
  };
  "routes/dashboard.experiments.$id._index.tsx": {
    id: "routes/dashboard.experiments.$id._index";
    page: "/dashboard/experiments/:id";
  };
  "routes/dashboard.experiments.new.tsx": {
    id: "routes/dashboard.experiments.new";
    page: "/dashboard/experiments/new";
  };
  "routes/dashboard.lift-assist.tsx": {
    id: "routes/dashboard.lift-assist";
    page: "/dashboard/lift-assist";
  };
  "routes/dashboard.segments.tsx": {
    id: "routes/dashboard.segments";
    page: "/dashboard/segments" | "/dashboard/segments/new";
  };
  "routes/dashboard.segments._index.tsx": {
    id: "routes/dashboard.segments._index";
    page: "/dashboard/segments";
  };
  "routes/dashboard.segments.new.tsx": {
    id: "routes/dashboard.segments.new";
    page: "/dashboard/segments/new";
  };
  "routes/dashboard.settings.tsx": {
    id: "routes/dashboard.settings";
    page: "/dashboard/settings";
  };
  "routes/dashboard.billing.tsx": {
    id: "routes/dashboard.billing";
    page: "/dashboard/billing";
  };
  "routes/dashboard.results.tsx": {
    id: "routes/dashboard.results";
    page: "/dashboard/results";
  };
  "routes/dashboard._index.tsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/webhooks.tsx": {
    id: "routes/webhooks";
    page: "/webhooks";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/experiments" | "/app/experiments/:id" | "/app/experiments/:id/variants/:variantId" | "/app/experiments/new" | "/app/lift-assist" | "/app/segments" | "/app/settings" | "/app/billing" | "/app/results";
  };
  "routes/app.experiments.tsx": {
    id: "routes/app.experiments";
    page: "/app/experiments" | "/app/experiments/:id" | "/app/experiments/:id/variants/:variantId" | "/app/experiments/new";
  };
  "routes/app.experiments._index.tsx": {
    id: "routes/app.experiments._index";
    page: "/app/experiments";
  };
  "routes/app.experiments.$id.tsx": {
    id: "routes/app.experiments.$id";
    page: "/app/experiments/:id" | "/app/experiments/:id/variants/:variantId";
  };
  "routes/app.experiments.$id.variants.$variantId.tsx": {
    id: "routes/app.experiments.$id.variants.$variantId";
    page: "/app/experiments/:id/variants/:variantId";
  };
  "routes/app.experiments.$id._index.tsx": {
    id: "routes/app.experiments.$id._index";
    page: "/app/experiments/:id";
  };
  "routes/app.experiments.new.tsx": {
    id: "routes/app.experiments.new";
    page: "/app/experiments/new";
  };
  "routes/app.lift-assist.tsx": {
    id: "routes/app.lift-assist";
    page: "/app/lift-assist";
  };
  "routes/app.segments.tsx": {
    id: "routes/app.segments";
    page: "/app/segments";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.billing.tsx": {
    id: "routes/app.billing";
    page: "/app/billing";
  };
  "routes/app.results.tsx": {
    id: "routes/app.results";
    page: "/app/results";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.config.$shopDomain": typeof import("./app/routes/api.config.$shopDomain.ts");
  "routes/storefront.embed[.js]": typeof import("./app/routes/storefront.embed[.js].tsx");
  "routes/api.assign": typeof import("./app/routes/api.assign.tsx");
  "routes/api.events": typeof import("./app/routes/api.events.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/dashboard.experiments": typeof import("./app/routes/dashboard.experiments.tsx");
  "routes/dashboard.experiments._index": typeof import("./app/routes/dashboard.experiments._index.tsx");
  "routes/dashboard.experiments.$id": typeof import("./app/routes/dashboard.experiments.$id.tsx");
  "routes/dashboard.experiments.$id.variants.$variantId": typeof import("./app/routes/dashboard.experiments.$id.variants.$variantId.tsx");
  "routes/dashboard.experiments.$id._index": typeof import("./app/routes/dashboard.experiments.$id._index.tsx");
  "routes/dashboard.experiments.new": typeof import("./app/routes/dashboard.experiments.new.tsx");
  "routes/dashboard.lift-assist": typeof import("./app/routes/dashboard.lift-assist.tsx");
  "routes/dashboard.segments": typeof import("./app/routes/dashboard.segments.tsx");
  "routes/dashboard.segments._index": typeof import("./app/routes/dashboard.segments._index.tsx");
  "routes/dashboard.segments.new": typeof import("./app/routes/dashboard.segments.new.tsx");
  "routes/dashboard.settings": typeof import("./app/routes/dashboard.settings.tsx");
  "routes/dashboard.billing": typeof import("./app/routes/dashboard.billing.tsx");
  "routes/dashboard.results": typeof import("./app/routes/dashboard.results.tsx");
  "routes/dashboard._index": typeof import("./app/routes/dashboard._index.tsx");
  "routes/webhooks": typeof import("./app/routes/webhooks.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.experiments": typeof import("./app/routes/app.experiments.tsx");
  "routes/app.experiments._index": typeof import("./app/routes/app.experiments._index.tsx");
  "routes/app.experiments.$id": typeof import("./app/routes/app.experiments.$id.tsx");
  "routes/app.experiments.$id.variants.$variantId": typeof import("./app/routes/app.experiments.$id.variants.$variantId.tsx");
  "routes/app.experiments.$id._index": typeof import("./app/routes/app.experiments.$id._index.tsx");
  "routes/app.experiments.new": typeof import("./app/routes/app.experiments.new.tsx");
  "routes/app.lift-assist": typeof import("./app/routes/app.lift-assist.tsx");
  "routes/app.segments": typeof import("./app/routes/app.segments.tsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/app.billing": typeof import("./app/routes/app.billing.tsx");
  "routes/app.results": typeof import("./app/routes/app.results.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
};